### ISSUE TITLE
Provide an example of output

### ISSUE THREAD

**Issue by 3vivekb** [line72/gtfs2metro#1]
It would be helpful if an image of the final output could be provided in the Readme.

**Comment by line72** [comment]
I agree, I need to make this more generic as it is very tied to a specific gtfs feed.

In the meantime, to get this working, open up gtfs2metro.py, and on line 72, you'll see this:

``` python
        #!mwd - sure wish the data used the direciton flag!!
        #  not this crappy hack
        # only look at outbound routes
        if trip.GetStopTimes()[0].stop.stop_name != 'Central Station' and \
           'ob' not in trip.shape_id and 'OB' not in trip.shape_id:
            continue
```

Comment this whole section out since it only works with the bjcta data feed:

``` python
        # #!mwd - sure wish the data used the direciton flag!!
        # #  not this crappy hack
        # # only look at outbound routes
        # if trip.GetStopTimes()[0].stop.stop_name != 'Central Station' and \
        #    'ob' not in trip.shape_id and 'OB' not in trip.shape_id:
        #     continue
```

Now you can run it like the following:

```
$ mkdir output
$ python gtfs2metro.py /path/to/gtfs.zip output/
```

This will generate a .svg file for each route in the gtfs transit zip file.

Also, you can modify _landmarks.py_ if you want to highlight landmarks. This is a dictionary, where the key is the stop id in the transit feed, and the value is a single item tuple of the Landmark name. It is also possible to extend the _connections.py_, and modify the last line in a similar way to specify a connection to an airport or trainstation at a specific stop. If I recall, it only correctly draws an airport icon.

If you need to look up the stop ids, I suggest using the schedule_viewer.py program that comes with Google's GTFS python library.

The output will look similar to the following:

![1](https://cloud.githubusercontent.com/assets/3654433/18927883/505cfdf0-8583-11e6-8ea0-91d3d07a2c7b.png)

![3](https://cloud.githubusercontent.com/assets/3654433/18927888/5a443fae-8583-11e6-9a78-17713eca1588.png)

**Comment by 3vivekb** [comment]
OO.  Pretty.  Maybe i'll try it out.
